# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Class-Journal
version:      0.01
version_from: lib/DBIx/Class/Schema/Journal.pm
installdirs:  site
requires:
    DBD::SQLite:                   0.12
    DBIx::Class:                   0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
