--- #YAML:1.0
name:                DBIx-Class-Journal
version:             0.900001_01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    DBD::SQLite:                   0.12
    DBIx::Class:                   0.08
    Test::TempDir:                 0.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
